version: '3'
services:
  my-mongo-task:
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data_tasksList:/data/db